// Auto-generated by: pnpm db:generate
// Run `pnpm db:generate` after any migration change to update this file.

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
